name: apiverve_imageconverter
description: Image Converter transforms images between formats. Convert HEIC from iPhones, modern WebP and AVIF formats, or classic PNG, JPG, GIF, and TIFF. Includes optional resizing and quality control.
version: 1.1.14
homepage: https://apiverve.com/marketplace/imageconverter?utm_source=dart&utm_medium=homepage
repository: https://github.com/apiverve/imageconverter-api/tree/main/dart

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  http: ^1.1.0
  http_parser: ^4.0.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
